services:
  allure:
    container_name: allure-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:

      - # путь до репозитория:/app/repo
      - allure-report:/app/reports
      - test-report:/app/reports/allure-test
    ports:
      - "9090:9090"
    tty: true


volumes:
  allure-report:
  test-report:
