services:
  allure:
    container_name: allure-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - # путь до репозитория:/app/repo
      - allure-test:/app/reports/allure-test
      - allure-report:/app/reports/allure-report
    ports:
      - "9090:9090"
    tty: true

volumes:
  allure-test:
  allure-report: